name: Determine Version
description: >
  Computes a final version string from GitVersion outputs and release context.
  For manual releases, extracts the version from the tag. For automatic releases,
  formats as {semver}-{prefix}.{number}.

inputs:
  is-manual-release:
    description: Whether this is a manual (GitHub Release) triggered release
    required: true
  release-tag-name:
    description: The release tag name (for manual releases, e.g. v1.2.3)
    required: false
    default: ''
  release-prerelease:
    description: Whether the GitHub release is marked as prerelease
    required: false
    default: 'false'
  semver:
    description: The majorMinorPatch from GitVersion (e.g. 1.2.3)
    required: false
    default: ''
  prerelease-number:
    description: The preReleaseNumber from GitVersion
    required: false
    default: ''
  commits-since:
    description: The commitsSinceVersionSource from GitVersion
    required: false
    default: ''
  prerelease-prefix:
    description: 'Prefix for prerelease versions (e.g. pre, beta, rc)'
    required: false
    default: 'pre'

outputs:
  version:
    description: The computed version string
    value: ${{ steps.compute.outputs.version }}
  is_prerelease:
    description: Whether this is a prerelease build
    value: ${{ steps.compute.outputs.is_prerelease }}

runs:
  using: composite
  steps:
    - name: Compute version
      id: compute
      shell: bash
      run: |
        if [[ "${{ inputs.is-manual-release }}" == "true" ]]; then
          TAG="${{ inputs.release-tag-name }}"
          VERSION="${TAG#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=${{ inputs.release-prerelease }}" >> $GITHUB_OUTPUT
          echo "Manual release version: $VERSION"
        else
          SEMVER="${{ inputs.semver }}"
          PRE_NUM="${{ inputs.prerelease-number }}"
          COMMITS="${{ inputs.commits-since }}"
          PREFIX="${{ inputs.prerelease-prefix }}"

          # Calculate initial prerelease number from GitVersion
          if [[ -n "$PRE_NUM" && "$PRE_NUM" != "0" ]]; then
            COMPUTED_NUM="$PRE_NUM"
          else
            COMPUTED_NUM="${COMMITS:-1}"
          fi

          # Find the highest existing prerelease number for this semver from git tags
          # This prevents version regression when tags reset the commit count
          # Ensure tags are fetched (checkout may not fetch all tags)
          git fetch --tags --force 2>/dev/null || true

          HIGHEST_EXISTING=0
          # Match tags like: preview-v0.7.3-pre.7, v0.7.3-pre.7, 0.7.3-pre.7
          echo "Scanning for existing tags matching *${SEMVER}-${PREFIX}.*"
          for tag in $(git tag -l "*${SEMVER}-${PREFIX}.*" 2>/dev/null || true); do
            echo "  Found tag: $tag"
            # Extract the number after the last dot
            NUM=$(echo "$tag" | grep -oE "${PREFIX}\.[0-9]+" | grep -oE "[0-9]+$" || true)
            if [[ -n "$NUM" && "$NUM" -gt "$HIGHEST_EXISTING" ]]; then
              HIGHEST_EXISTING="$NUM"
            fi
          done

          # Ensure we always increment past the highest existing version
          if [[ "$COMPUTED_NUM" -le "$HIGHEST_EXISTING" ]]; then
            FINAL_NUM=$((HIGHEST_EXISTING + 1))
            echo "::warning::GitVersion computed ${PREFIX}.${COMPUTED_NUM} but ${PREFIX}.${HIGHEST_EXISTING} already exists. Incrementing to ${PREFIX}.${FINAL_NUM}"
          else
            FINAL_NUM="$COMPUTED_NUM"
          fi

          VERSION="${SEMVER}-${PREFIX}.${FINAL_NUM}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=true" >> $GITHUB_OUTPUT
          echo "Automatic prerelease version: $VERSION (computed: ${COMPUTED_NUM}, highest existing: ${HIGHEST_EXISTING})"
        fi
